Update COSMO CD630
COSMO was applied to Clostridium difficile 630 genome (CD630)

diff --git a/.github/COSMO CD630 b/.github/COSMO CD630
--- a/.github/COSMO CD630
+++ b/.github/COSMO CD630
@@ -1,1 +1,10 @@
+#!/bin/bash
+
+
+if [[ -z "$(which COSMO)" ]] ; then
+	echo "COSMO not found, do you maybe need to do conda activate cosmo?" >&2
+	exit 1
+fi
+
+COSMO -D 1 -d 2 -F 5.0 -f 10.0 -o Wildtype_Control1.csv 'gi|126697566|ref|NC_009089.1|' 4290252  " $(pwd)\ Wildtype_Control1.bam"/ " $(pwd)/NC_009089.1.gff"
 
